export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_PLAYING_CURRENT_TIME = 'SET_PLAYING_CURRENT_TIME'

export const SET_PLAYING_LIST = 'SET_PLAYING_LIST'

// 随机播放模式下实际的播放列表
export const SET_PLAYING_LIST_REALL = 'SET_PLAYING_LIST_REALL'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'
